version: '2'
services:
  web:
    build: .
    environment:
      - 'PORT=8080'
    volumes:
      # only really for development
      # should let the dockerfile build in the right files in other cases
      - ${PWD}:/service
    ports:
      - '4000:8080'
    links:
      - cache
    command: npm run start
  cache:
    image: redis
